### PR TITLE
Begin converting the organization maturity matrix

### PR DESCRIPTION
**Pull request by amaltson**
This PR starts the process of converting the Excel based InnerSource Maturity Matrix into a Markdown document. Per discussion and agreement in #46, we're going to try a flat file approach to representing the maturity matrix.

This PR starts with the Organization InnerSource Maturity Matrix. It merges the Overview section into the document, with the Matrix itself in the middle of the document.

### CODE REVIEW

**Review by claredillon — COMMENTED** [review]
Looks good to me as the starting point!

**Review by mcleo-d — COMMENTED** [review]
From live review on https://github.com/finos/InnerSource/issues/48

`docs/maturity-matrix/organization-maturity-matrix.md` to become `docs/maturity-matrix/README.md`

**Comment by amaltson** [comment]
Thanks all for the review during #48. Made the discussed changes, hopefully good to merge 😄

**Review by mcleo-d — COMMENTED** [review]
@claredillon and @amaltson - The following file content is not complete and needs to be tracked centrally to completion.

`docs/maturity-matrix/organization-maturity-matrix.md`

**Pull request merged**
