### PR TITLE
Add Maturity Matrix Excel sheet

### PR DESCRIPTION
**Pull request by amaltson**
Ensure we maintain a copy of the maturity matrix that was posted to the GitHub
Discussions in source control before we transform it into a table.

In a subsequent PR we'll turn this into an HTML table.

### CODE REVIEW

**Comment by mcleo-d** [comment]
Hi @amaltson - Can you check with @claredillon the Excel sheet contributed into the repo is the latest release version as the following Discussion does have the correct versions uploaded as PDFs.

https://github.com/finos/InnerSource/discussions/12#discussioncomment-1022570

**Comment by amaltson** [comment]
> Hi @amaltson - Can you check with @claredillon the Excel sheet contributed by this PR is the latest release version as the following Discussion does have the correct versions uploaded as PDFs.
> 
> [#12 (comment)](https://github.com/finos/InnerSource/discussions/12#discussioncomment-1022570)
> 
> Screenshot 2021-11-03 at 13 01 37

I grabbed the [Excel file from @claredillon comment](https://github.com/finos/InnerSource/discussions/12#discussioncomment-816795). I skipped the PDFs as they can't be changed and I figured we want to keep something that's more source controllable and changeable.

Looking into the automatic conversion, we'll actually need to export each Spreadsheet into a CSV and then run `pandoc` on that. I'll try to give that a whirl soon.

> Also, we need to capture the feedback provided by @aaronsearle in the discussion below. Maybe this should now be raised as an Issue once this PR has been accepted and merged?
> 
> [#12 (reply in thread)](https://github.com/finos/InnerSource/discussions/12#discussioncomment-1088090)

Agreed, let's do that as a separate commit to show our work 😄

**Review by godds — APPROVED** [review]
Looks good to me

**Pull request merged**
