### PR TITLE
Initial pass at Docusaurus website

### PR DESCRIPTION
**Pull request by godds**
@amaltson Here's a first pass at styling and configuring the Docusaurus site so that we have something workable, with it building through netlify. Can you review, please?

### CODE REVIEW

**Comment by mcleo-d** [comment]
#64 has been raised and merged to fix broken links that were stopping `netflify` from deploying through `yarn build`.

**Comment by mcleo-d** [comment]
Hi @godds,

Thanks for resolving the issues that were causing build difficulties 👍🏻 

Can you update the main contribution description as it would be great for @amaltson to approve now the microsite is building through `netlify` - https://github.com/finos/InnerSource/pull/62#issue-1228933669

I can then organise an InnerSource subdomain through the FINOS team.

Many thanks,

James.

**Comment by mcleo-d** [comment]
@eminty69 and @amaltson 👋🏻 

It would be awesome if you could approve and merge this pull request if acceptable.

Many thanks,

James.

**Comment by amaltson** [comment]
Hey, sorry about that. I've been out of commission but have started taking a look. I'll get this merged ASAP.

**Comment by eminty69** [comment]
@amaltson  Thanks for taking care of this.  I'm currently not able to make open source contributions in my new role but I'm looking at how to get inner source SIG approved

**Comment by eminty69** [comment]
Perhaps updating my organization on the new website might be a convincing argument :-)

**Comment by amaltson** [comment]
Are you at RBC now? Maybe Anthony can help in that area?

**Comment by anvacca** [comment]
@amaltson, working on getting more people access to GitHub :)

**Comment by eminty69** [comment]
Don't worry - I've already been bugging Anthony!

**Pull request merged**
